<table class='read'>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($controller->output as $value) { ?>
        <tr>
            <td><?php echo $value['page_id'] ?></td>
            <td><?php echo $value['page_name'] ?></td>
            <td><a href='?controller=crud&amp;action=update&amp;id=<?php echo $value['page_id'] ?>'>EDIT</a></td>
            <td><a href='?controller=crud&amp;action=delete&amp;id=<?php echo $value['page_id'] ?>'>[X]</a></td>
        </tr>
    <?php } ?>
    <tr>
        <td>
            <a href='?controller=crud&amp;action=create'>[ADD]</a>
        </td>
</table>